[package]
name = "test-file"
version = "0.1.0"
authors = ["pluto <Plutonium130@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.12.35"
hyper-tls = "0.3.2"
pretty_env_logger = "0.3.1"
futures = "0.3.1"